import { Clover, Search } from 'lucide-react'
import React from 'react'


const NotFound = () => {
  return (
    <div className='flex flex-col min-h-[70vh] w-full justify-center items-center gap-12'>
      <Clover size={200} className='stroke-primary'/>
      <div className='felx flex-col items-center justify-center text-center si'>
        <p className='text-3xl font-semibold text-primary'>
          Nothing to see here
        </p>
        <p className='text-accent-foreground font-normal'>
          So here is a random image generated by <span className='text-app'> Creative AI</span>
        </p>
      </div>
    </div>
  )
}

export default NotFound