import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} !min-h-[calc(100vh-1px)] flex flex-col antialiased`}
          suppressHydrationWarning
        >
            <main className="relative flex-1 flex flex-col bg-brand-25 text-brand-950 ">
              {children}
              <Toaster />
            </main>
        </body>
      </html>
  );
}
